In [2]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [11]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])
print(" === Zomato Sales Analysis === ")
salesDataShape = sales_data.shape
print("\n Sales data shape", salesDataShape)
print("\n Sample data for 1st 3 restaurant: ", sales_data[:3])
print("\n Printing Data without ID")
print("\n Sample data for 1st 3 restaurant: ", sales_data[: , 1:])


 === Zomato Sales Analysis === 

 Sales data shape (5, 5)

 Sample data for 1st 3 restaurant:  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

 Printing Data without ID

 Sample data for 1st 3 restaurant:  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
