## Numpy

learn about numpy with chai aur code


In [1]:
import numpy as np

Creatin array from list


In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [3]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array  = np.array([1, 2, 3])
print("Python array multiplication ", np_array * 2)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [4]:
import time 
start = time.time()
py_list = [i*2 for i  in range(1000000)]
print("\n List operation time: ", time.time() - start) 

start = time.time()
np_array = np.arange(1000000) * 2 
print("\n Numpy operation time: ", time.time() - start) 


 List operation time:  0.14803409576416016

 Numpy operation time:  0.012472391128540039


### Creating array from scratch


In [5]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
print("Ones array: \n", ones)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
full = np.full((2,2), 7)
print("Full array: \n", full)

random = np.random.random((2, 3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)


Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.10333706 0.93249885 0.76216734]
 [0.06600014 0.5755701  0.38435658]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor


In [7]:
vector = np.array([1,2,3])
print("\n Vector: ", vector)

matrix = np.array(
                    [
                    [1, 2, 3],
                    [4, 5, 6]
                    ]
                    )
print("\n Matrix: ", matrix)

tensor = np.array([
    [
     [1, 2], 
     [3, 4]], 
     [
     [5, 6], 
     [7, 8]
     ]
     ])
print("\n Tensor: ", tensor)


 Vector:  [1 2 3]

 Matrix:  [[1 2 3]
 [4 5 6]]

 Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties


In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape ", arr.shape)
print("Dimension ", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)


Shape  (2, 3)
Dimension  2
Size 6
DType int64


# Array Reshaping


In [11]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel ( returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose 
transponse = reshaped.T
print("\n Transpose array ", transponse)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
