## Numpy Array operations


In [1]:
import numpy as np 

In [2]:
arr  = np.array([i for i in range(10)])
print("Array: ", arr)
print("Basic slicing ", arr[2:7])
print("With step slicing ", arr[1:8:2])


Array:  [0 1 2 3 4 5 6 7 8 9]
Basic slicing  [2 3 4 5 6]
With step slicing  [1 3 5 7]


In [3]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Specific Element ", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire  column: ", arr_2d[: , 1])

Specific Element  6
Entire row:  [4 5 6]
Entire  column:  [2 5 8]


In [4]:
unsorted = np.array([3, 1, 3, 45 , 23 ])
print("Sorted Array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[2, 3], [3, 1], [2, 3]])
print("Sorted 2D array by column: ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array by row: ", np.sort(arr_2d_unsorted, axis=1))

Sorted Array:  [ 1  3  3 23 45]
Sorted 2D array by column:  [[2 1]
 [2 3]
 [3 3]]
Sorted 2D array by row:  [[2 3]
 [1 3]
 [2 3]]


## Filter


In [5]:
numbers = np.array([i for i in range(1, 10)])
even_number  = numbers[numbers % 2 == 0]
print("Even numbers ", even_number)

Even numbers  [2 4 6 8]


### Filter with Mask


In [6]:
mask = numbers > 5 
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [6 7 8 9]


## Fancy indexing vs np.where()


In [7]:
indicies = [0, 2, 4]
print(numbers[indicies])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where ", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8]),)
NP where  [6 7 8 9]


In [8]:
condition_array = np.where(numbers > 5, "True", "False")
print(condition_array)

# if(numbers > 5){return "True"}else{return "False"}

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True']


# Adding and removing data


In [9]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print("Combined array ", combined)

Combined array  [1 2 3 4 5 6]


# Array compatiblity


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 4,5, 6])
c = np.array([7, 8, 9])

print("Compatiblity shapes ", a.shape == b.shape)

Compatiblity shapes  False


In [15]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)

print("\n\n")
new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(original)
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]



[[1 2]
 [3 4]]
[[1 2 7]
 [3 4 8]]


In [17]:
arr = np.array([1, 2, 3, 4])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4]
