## Numpy

learn about numpy with chai aur code


In [1]:
import numpy as np

Creatin array from list


In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [3]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array  = np.array([1, 2, 3])
print("Python array multiplication ", np_array * 2)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]


In [9]:
import time 
start = time.time()
py_list = [i*2 for i  in range(1000000)]
print("\n List operation time: ", time.time() - start) 

start = time.time()
np_array = np.arange(1000000) * 2 
print("\n Numpy operation time: ", time.time() - start) 


 List operation time:  0.08390164375305176

 Numpy operation time:  0.08186078071594238


### Creating array from scratch


In [10]:
zeros = np.zeros((3, 4))
print("Zeros array: \n", zeros)

ones = np.ones((2, 3))
print("Ones array: \n", ones)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
full = np.full((2,2), 7)
print("Full array: \n", full)

random = np.random.random((2, 3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)


Full array: 
 [[7 7]
 [7 7]]
Random array: 
 [[0.14693627 0.7002601  0.58911153]
 [0.51903236 0.40123996 0.8458161 ]]
Sequence array: 
 [ 0  2  4  6  8 10]


### Vector, Matrix and Tensor


In [ ]:
vector = np.array([1,2,3])
print("\n Vector: ", vector)

matrix = np.array(
                    [
                    [1, 2, 3],
                    [4, 5, 6]
                    ]
                    )
print("\n Matrix: ", matrix)

tensor = np.array([
    [
     [1, 2], 
     [3, 4]], 
     [
     [5, 6], 
     [7, 8]
     ]
     ])
print("\n Tensor: ", tensor)


 Vector:  [1 2 3]

 Matrix:  [[1 2 3]
 [4 5 6]]
