### 2. Autograd

The autograd package provides automatic differentiation for all operations on Tensors. Generally speaking, torch.autograd is an engine for computing the vector-Jacobian product. It computes partial derivatives while applying the chain rule.


In [1]:
import torch
import numpy as np

In [2]:
# requires_grad = True --> tracks all operations on the tensor. 
x = torch.randn(3, requires_grad=True )
y = x + 2 

# y was created as a result of an operation, so it has a grad_fn attribute
# grad_fn: references a Function that has created the Tensor
print(x)
print(y)
print(y.grad_fn)

tensor([ 0.4397, -1.2977, -0.8586], requires_grad=True)
tensor([2.4397, 0.7023, 1.1414], grad_fn=<AddBackward0>)


In [3]:
# Do more operations of y 
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([17.8562,  1.4798,  3.9081], grad_fn=<MulBackward0>)
tensor(7.7480, grad_fn=<MeanBackward0>)


In [4]:
# Let's compute the graidients with backpropogation
# When we finish our computation we can  call .backward() and have all the gradients computer automatically. 
# The gradient for this tensor will be accumulated into .grad attribute. 
# It is the partial derivate of the function w.r.t. the tensor

z = y * y * 3
print(z)
z = z.mean()
print(z)


# ! ! ! Careful ! ! ! backward() accumulate the gradient for this tensor into .grad attribute. 
# ! ! ! We need to be careful during optimization ! ! ! optimizer.zero_grad()

tensor([17.8562,  1.4798,  3.9081], grad_fn=<MulBackward0>)
tensor(7.7480, grad_fn=<MeanBackward0>)


In [5]:
z.backward()
print(x.grad)

tensor([4.8794, 1.4047, 2.2827])
