### 1. Tensors


In [1]:
import torch
import numpy as np

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print("empty(1):", x)
x = torch.empty(3) # vector
print("empty(3):",x)
x = torch.empty(2, 3) # matrix
print("empty(2,3):",x)
x = torch.empty(2, 2, 3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print("empty(2, 2, 3):",x)

# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print("rand(5,3):", x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print("zeros(5,3):", x)

empty(1): tensor([-4.1246e+11])
empty(3): tensor([0., 0., 0.])
empty(2,3): tensor([[0., 0., 0.],
        [0., 0., 0.]])
empty(2, 2, 3): tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
rand(5,3): tensor([[0.3483, 0.0935, 0.5112],
        [0.2793, 0.2186, 0.3692],
        [0.0696, 0.5560, 0.3710],
        [0.7165, 0.8387, 0.7937],
        [0.8822, 0.8945, 0.7685]])
zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [2]:
# Check Size 
print("Size : " , x.size())
print("Shape : " , x.shape)

Size :  torch.Size([5, 3])
Shape :  torch.Size([5, 3])


In [3]:
# Check Datatype
print(x.dtype)

# Spcify types, float32 default
x = torch.zeros(5,3, dtype=torch.float16)
print(x)

# Check Type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [4]:
# Construct from data 
x  = torch.tensor([5, 5, 3 ])
print(x, x.dtype)

tensor([5, 5, 3]) torch.int64


In [5]:
# Requires_grad argument 
# This will tell pytorch that it will need to calcuate the gradient for this tensor 
# Later in your optimization steps 
# i.e. this is a variable in your model that you want to optimize 

x = torch.tensor([5.5,3], requires_grad=True)
print(x) 


tensor([5.5000, 3.0000], requires_grad=True)


In [6]:
# Operations
x = torch.ones(2, 2)
y = torch.rand(2, 2)

# Elementwise addition
z = x + y
torch.add(x,y)
# torch.add(x,y)

#In plane addition, everything with a  trailing underscore is a inplace operation
#i.e. it will modify the variable
# y.add_(x)

print(x)
print(y)
print("Addition : ", z)

z = x - y 
torch.sub(x, y)
print("Subtraction : ", z)

z = x * y 
torch.mul(x, y)
print("Multiplication : ", z)

z = x / y 
torch.div(x, y)
print("Division : ", z)


tensor([[1., 1.],
        [1., 1.]])
tensor([[0.1235, 0.1542],
        [0.0303, 0.9287]])
Addition :  tensor([[1.1235, 1.1542],
        [1.0303, 1.9287]])
Subtraction :  tensor([[0.8765, 0.8458],
        [0.9697, 0.0713]])
Multiplication :  tensor([[0.1235, 0.1542],
        [0.0303, 0.9287]])
Division :  tensor([[ 8.0940,  6.4846],
        [32.9575,  1.0768]])


In [7]:
# Slicing 
x = torch.rand(5, 3)
print(x)
print("X[: , 0] ", x[: , 0 ])
print("X[1, :] ", x[1, :  ])
print("X[1, 1] ", x[1, 1])

print("x[1, 1].item() ", x[1,1].item())

tensor([[0.3838, 0.3710, 0.6569],
        [0.5449, 0.5527, 0.6332],
        [0.0711, 0.9078, 0.8720],
        [0.3815, 0.1849, 0.2858],
        [0.2061, 0.3853, 0.9112]])
X[: , 0]  tensor([0.3838, 0.5449, 0.0711, 0.3815, 0.2061])
X[1, :]  tensor([0.5449, 0.5527, 0.6332])
X[1, 1]  tensor(0.5527)
x[1, 1].item()  0.5526584982872009


In [8]:
# Reshape with torch.view()
x = torch.randn(4, 4) 
y = x.view(16) # Shapes the x as (16, ) in y
z = x.view(-1, 8) # The -1 tells PyTorch to infer the appropriate dimension automatically based on the total number of elements

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### NumPy

#### Converting a Torch to a NumPy array and vice versa is very easy.


In [9]:
import torch

a = torch.ones(5)
print(a)

b = a.numpy()
print(b)
print(type(b))


tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [10]:
# Numpy to torch with .from_numpy(x), or torch.tensor() to copy it 
a = np.ones(5)
b = torch.from_numpy(a)
c = torch.tensor(a)
print(a)
print(b)
print(c)

# Again be careful when modifying
a += 1 
print(a)
print(b)
print(c)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


### GPU Support

#### By default are created on the CPU. But we can also move them to the GPU (if it's available), or create them direcly on the GPU


In [11]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2, 2).to(device) # Move tensors to GPU device 
# x = a.to("cpu")
# x = x.to('cuda')

x = torch.rand(2, 2, device=device) # or directly create them on GPU 

### 2. Autograd

The autograd package provides automatic differentiation for all operations on Tensors. Generally speaking, torch.autograd is an engine for computing the vector-Jacobian product. It computes partial derivatives while applying the chain rule.


In [12]:
# requires_grad = True --> tracks all operations on the tensor. 
x = torch.randn(3, requires_grad=True )
y = x + 2 

# y was created as a result of an operation, so it has a grad_fn attribute
# grad_fn: references a Function that has created the Tensor
print(x)
print(y)
print(y.grad_fn)

tensor([-0.1092, -0.4746,  0.2976], requires_grad=True)
tensor([1.8908, 1.5254, 2.2976], grad_fn=<AddBackward0>)


In [13]:
# Do more operations of y 
z = y * y * 3
print(z)
z = z.mean()
print(z)

tensor([10.7248,  6.9805, 15.8373], grad_fn=<MulBackward0>)
tensor(11.1809, grad_fn=<MeanBackward0>)


In [14]:
# Let's compute the graidients with backpropogation
# When we finish our computation we can  call .backward() and have all the gradients computer automatically. 
# The gradient for this tensor will be accumulated into .grad attribute. 
# It is the partial derivate of the function w.r.t. the tensor

z = y * y * 3
print(z)
z = z.mean()
print(z)


# ! ! ! Careful ! ! ! backward() accumulate the gradient for this tensor into .grad attribute. 
# ! ! ! We need to be careful during optimization ! ! ! optimizer.zero_grad()

tensor([10.7248,  6.9805, 15.8373], grad_fn=<MulBackward0>)
tensor(11.1809, grad_fn=<MeanBackward0>)


In [15]:
z.backward()
print(x.grad)

tensor([3.7815, 3.0508, 4.5953])
