### 1. Tensors


In [2]:
import torch

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print("empty(1):", x)
x = torch.empty(3) # vector
print("empty(3):",x)
x = torch.empty(2, 3) # matrix
print("empty(2,3):",x)
x = torch.empty(2, 2, 3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print("empty(2, 2, 3):",x)

# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print("rand(5,3):", x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print("zeros(5,3):", x)

c:\Users\manoj\OneDrive\Desktop\.vs_code\Python\LearnPython\Theory\PyTorch\torch_env\Lib\site-packages\torch\_subclasses\functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


empty(1): tensor([0.])
empty(3): tensor([0., 0., 0.])
empty(2,3): tensor([[0., 0., 0.],
        [0., 0., 0.]])
empty(2, 2, 3): tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
rand(5,3): tensor([[0.3678, 0.1536, 0.4887],
        [0.0143, 0.2768, 0.7862],
        [0.2686, 0.3253, 0.7043],
        [0.8337, 0.6597, 0.7088],
        [0.9799, 0.2460, 0.2819]])
zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
# Check Size 
print("Size : " , x.size())
print("Shape : " , x.shape)

Size :  torch.Size([5, 3])
Shape :  torch.Size([5, 3])


In [8]:
# Check Datatype
print(x.dtype)

# Spcify types, float32 default
x = torch.zeros(5,3, dtype=torch.float16)
print(x)

# Check Type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [9]:
# Construct from data 
x  = torch.tensor([5, 5, 3 ])
print(x, x.dtype)

tensor([5, 5, 3]) torch.int64


In [11]:
# Requires_grad argument 
# This will tell pytorch that it will need to calcuate the gradient for this tensor 
# Later in your optimization steps 
# i.e. this is a variable in your model that you want to optimize 

x = torch.tensor([5.5,3], requires_grad=True)
print(x) 


tensor([5.5000, 3.0000], requires_grad=True)


In [15]:
# Operations
x = torch.ones(2, 2)
y = torch.rand(2, 2)

# Elementwise addition
z = x + y
torch.add(x,y)
# torch.add(x,y)

#In plane addition, everything with a  trailing underscore is a inplace operation
#i.e. it will modify the variable
# y.add_(x)

print(x)
print(y)
print("Addition : ", z)

z = x - y 
torch.sub(x, y)
print("Subtraction : ", z)

z = x * y 
torch.mul(x, y)
print("Multiplication : ", z)

z = x / y 
torch.div(x, y)
print("Division : ", z)


tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5894, 0.3779],
        [0.9377, 0.5991]])
Addition :  tensor([[1.5894, 1.3779],
        [1.9377, 1.5991]])
Subtraction :  tensor([[0.4106, 0.6221],
        [0.0623, 0.4009]])
Multiplication :  tensor([[0.5894, 0.3779],
        [0.9377, 0.5991]])
Division :  tensor([[1.6967, 2.6462],
        [1.0665, 1.6691]])


In [16]:
# Slicing 
x = torch.rand(5, 3)
print(x)
print("X[: , 0] ", x[: , 0 ])
print("X[1, :] ", x[1, :  ])
print("X[1, 1] ", x[1, 1])

print("x[1, 1].item() ", x[1,1].item())

tensor([[0.0103, 0.5702, 0.2058],
        [0.8807, 0.2082, 0.0537],
        [0.4114, 0.0852, 0.4756],
        [0.4663, 0.7731, 0.0342],
        [0.3840, 0.3547, 0.0573]])
X[: , 0]  tensor([0.0103, 0.8807, 0.4114, 0.4663, 0.3840])
X[1, :]  tensor([0.8807, 0.2082, 0.0537])
X[1, 1]  tensor(0.2082)
x[1, 1].item()  0.20821809768676758
