### 1. Tensors


In [1]:
import torch
import numpy as np

# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print("empty(1):", x)
x = torch.empty(3) # vector
print("empty(3):",x)
x = torch.empty(2, 3) # matrix
print("empty(2,3):",x)
x = torch.empty(2, 2, 3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print("empty(2, 2, 3):",x)

# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print("rand(5,3):", x)

# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print("zeros(5,3):", x)

empty(1): tensor([3.8706e+25])
empty(3): tensor([0., 0., 0.])
empty(2,3): tensor([[0., 0., 0.],
        [0., 0., 0.]])
empty(2, 2, 3): tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
rand(5,3): tensor([[0.8392, 0.1522, 0.9456],
        [0.1599, 0.0984, 0.0883],
        [0.2543, 0.7842, 0.8470],
        [0.0730, 0.0693, 0.4106],
        [0.3078, 0.0744, 0.3951]])
zeros(5,3): tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [2]:
# Check Size 
print("Size : " , x.size())
print("Shape : " , x.shape)

Size :  torch.Size([5, 3])
Shape :  torch.Size([5, 3])


In [3]:
# Check Datatype
print(x.dtype)

# Spcify types, float32 default
x = torch.zeros(5,3, dtype=torch.float16)
print(x)

# Check Type
print(x.dtype)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
torch.float16


In [4]:
# Construct from data 
x  = torch.tensor([5, 5, 3 ])
print(x, x.dtype)

tensor([5, 5, 3]) torch.int64


In [5]:
# Requires_grad argument 
# This will tell pytorch that it will need to calcuate the gradient for this tensor 
# Later in your optimization steps 
# i.e. this is a variable in your model that you want to optimize 

x = torch.tensor([5.5,3], requires_grad=True)
print(x) 


tensor([5.5000, 3.0000], requires_grad=True)


In [6]:
# Operations
x = torch.ones(2, 2)
y = torch.rand(2, 2)

# Elementwise addition
z = x + y
torch.add(x,y)
# torch.add(x,y)

#In plane addition, everything with a  trailing underscore is a inplace operation
#i.e. it will modify the variable
# y.add_(x)

print(x)
print(y)
print("Addition : ", z)

z = x - y 
torch.sub(x, y)
print("Subtraction : ", z)

z = x * y 
torch.mul(x, y)
print("Multiplication : ", z)

z = x / y 
torch.div(x, y)
print("Division : ", z)


tensor([[1., 1.],
        [1., 1.]])
tensor([[0.8190, 0.5136],
        [0.9709, 0.9184]])
Addition :  tensor([[1.8190, 1.5136],
        [1.9709, 1.9184]])
Subtraction :  tensor([[0.1810, 0.4864],
        [0.0291, 0.0816]])
Multiplication :  tensor([[0.8190, 0.5136],
        [0.9709, 0.9184]])
Division :  tensor([[1.2210, 1.9472],
        [1.0299, 1.0889]])


In [7]:
# Slicing 
x = torch.rand(5, 3)
print(x)
print("X[: , 0] ", x[: , 0 ])
print("X[1, :] ", x[1, :  ])
print("X[1, 1] ", x[1, 1])

print("x[1, 1].item() ", x[1,1].item())

tensor([[0.4594, 0.4578, 0.0236],
        [0.7371, 0.0307, 0.0077],
        [0.7398, 0.1254, 0.2807],
        [0.7672, 0.6725, 0.4940],
        [0.8361, 0.6619, 0.7829]])
X[: , 0]  tensor([0.4594, 0.7371, 0.7398, 0.7672, 0.8361])
X[1, :]  tensor([0.7371, 0.0307, 0.0077])
X[1, 1]  tensor(0.0307)
x[1, 1].item()  0.03069692850112915


In [8]:
# Reshape with torch.view()
x = torch.randn(4, 4) 
y = x.view(16) # Shapes the x as (16, ) in y
z = x.view(-1, 8) # The -1 tells PyTorch to infer the appropriate dimension automatically based on the total number of elements

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
